In [22]:
# Abbreviations:
# DS: data set
# df: data frame
import csv
import pandas as pd
from sklearn.datasets import load_boston
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing

# Map string attributes to integer values
def map_stringAttributes(df, attr_hash):
    df_new = df.copy()
    le = preprocessing.LabelEncoder()
    #new_features = []
    #print("* len(df.columns)", len(df.columns), sep="\n", end="\n\n")
    for i in range (0, len(df.columns)-1, 1):
        attr_name = df.columns[i]                      # attribute name
        value = df.iloc[0][attr_name]                  # first value in column
        if (isinstance(value, str) == True):           # check if value is a string
            attr_values = df_new[attr_name].unique()   # unique values for attribute
            # map integers for each unique attribute value
            map_to_int = {name: n for n, name in enumerate(attr_values)}
            # replace data in dataset with its respective int
            df_new[attr_name] = df_new[attr_name].replace(map_to_int)
            # store list of attribute values and their int mapping to attribute name
            attr_hash[attr_name] = list(enumerate(attr_values))
            #print("* attr_hash[attr_name]", attr_hash[attr_name], end="\n\n")
    # view of new dataset with integer mapping
    print("* New data frame head:", df_new.head(20), end="\n\n")
    return (df_new, attr_hash)
        

# Data frames for their respective data set
adult_df = pd.read_csv("Adult_DS.csv")
boston_df = load_boston()

# Naive Bayes Classifier
# Create list of features for adult DS
adult_features = list(adult_df.columns[:14])
# This is just to show everything is working
print("* features:", adult_features, sep="\n", end="\n\n")
print("* classes:", adult_classes, sep="\n", end="\n\n")

# hash table for attributes
attributes = {}
adult_df, attributes = map_stringAttributes(adult_df, attributes)

adult_y = adult_df["annual-income"]        # class label
adult_X = adult_df[adult_features]         # features

gnb = GaussianNB()
# fit dataset
naive_bayes = gnb.fit(adult_X, adult_y)

* features:
['age', 'workclass', 'final-weight', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']

* classes:
['<=50K' '>50K']

* New data frame head:     age  workclass  final-weight  education  education-num  marital-status  \
0    39          0         77516          0             13               0
1    50          1         83311          0             13               1
2    38          2        215646          1              9               2
3    53          2        234721          2              7               1
4    28          2        338409          0             13               1
5    37          2        284582          3             14               1
6    49          2        160187          4              5               3
7    52          1        209642          1              9               1
8    31          2         45781          3             14               0
9    42          2        159449          0             13               1
10   37          2        280464          5             10               1
11   30          0        141297          0             13               1
12   23          2        122272          0             13               0
13   32          2        205019          6             12               0
14   40          2        121772          7             11               1
15   34          2        245487          8              4               1
16   25          1        176756          1              9               0
17   32          2        186824          1              9               0
18   38          2         28887          2              7               1
19   43          1        292175          3             14               2

    occupation  relationship  race  sex  capital-gain  capital-loss  \
0            0             0     0    0          2174             0
1            1             1     0    0             0             0
2            2             0     0    0             0             0
3            2             1     1    0             0             0
4            3             2     1    1             0             0
5            1             2     0    1             0             0
6            4             0     1    1             0             0
7            1             1     0    0             0             0
8            3             0     0    1         14084             0
9            1             1     0    0          5178             0
10           1             1     1    0             0             0
11           3             1     2    0             0             0
12           0             3     0    1             0             0
13           5             0     1    0             0             0
14           6             1     2    0             0             0
15           7             1     3    0             0             0
16           8             3     0    0             0             0
17           9             4     0    0             0             0
18           5             1     0    0             0             0
19           1             4     0    1             0             0

    hours-per-week  native-country annual-income
0               40               0         <=50K
1               13               0         <=50K
2               40               0         <=50K
3               40               0         <=50K
4               40               1         <=50K
5               40               0         <=50K
6               16               2         <=50K
7               45               0          >50K
8               50               0          >50K
9               40               0          >50K
10              80               0          >50K
11              40               3          >50K
12              30               0         <=50K
13              50               0         <=50K
14              40               4          >50K
15              45               5         <=50K
16              35               0         <=50K
17              40               0         <=50K
18              50               0         <=50K
19              45               0          >50K